config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root :to => "welcome#index"
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
  has_many :attendees, ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") }
  belongs_to :category, :optional => true
  has_one :location, :dependent => :destroy
  has_many :event_groupships
  has_many :groups, :through => :event_groupships
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :event_groupships
  has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :event
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate
  layout "admin"


  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == "username" && password == "password"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find( params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build( attendee_params )
    if @attendee.save
      redirect_to event_attendees_url( @event )
    else
      render :action => :new
    end
  end

  def edit
    @attendee = @event.attendees.find( params[:id] )
  end

  def update
    @attendee = @event.attendees.find( params[:id])

    if @attendee.update( attendee_params)
      redirect_to event_attendees_url( @event )
    else
      render :action => :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find( params[:id])
    @attendee.destroy

    redirect_to event_attendees_url( @event)
  end

  protected

  def find_event
    @event = Event.find( params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end
end

app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController
  before_action :find_event

  def show
    @location = @event.location
  end

  def new
    @location = @event.build_location
  end

  def create
    @location = @event.build_location( location_params)
    if @location.save
      redirect_to event_location_url( @event )
    else
      render :action => :new
    end
  end

  def edit
    @location = @event.location
  end

  def update
    @location = @event.location

    if @location.update( location_params)
      redirect_to event_location_url( @event )
    else
      render :action => :edit
    end
  end

  def destroy
    @location = @event.location
    @location.destroy

    redirect_to event_location_url( @event )
  end

  protected

  def find_event
    @event = Event.find( params[:event_id])
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [ :show, :edit, :update, :destroy]

  def index
    @events = Event.page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events.to_xml }
      format.json { render :json => @events.to_json }
      format.atom { @feed_title = "My event list" } # index.atom.builder
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_url(@event)
      flash[:notice] = "event was successfully updated"
    else
      render :action => :edit
    end
  end

  def show
    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml               # show.xml.builder
      format.json { render :json => { id: @event.id, name: @event.name }.to_json }
    end
  end

  def destroy
    @event.destroy

    redirect_to events_url
    flash[:alert] = "event was successfully deleted"
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to :action => :index
      flash[:notice] = "event was successfully created"
    else
      render :action => :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def say
  end

  def index
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => { :method => :patch } do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
    <li>
      <%= attendee.name %>
      <%= link_to 'show',event_attendee_path(@event, attendee) %>
      <%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
      <%= link_to 'destroy', event_attendee_path(@event, attendee), :method => :delete %>
    </li>
    <% end %>
</ul>

<%= link_to 'new attendee', new_event_attendee_path(@event) %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<p><%= @attendee.name %></p>

app/views/event_locations/edit.html.erb
<%= form_for @location, :url => event_location_path(@event), :method => :patch do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_locations/new.html.erb
<%= form_for @location, :url => event_location_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_locations/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.location %>
  <p><%= @event.location.name %></p>
  <p><%= link_to "edit", edit_event_location_path(@event) %></p>
  <p><%= link_to "destroy", event_location_path(@event), :method => :delete %></p>
<% else %>
  <p>N/A</p>
  <P><%= link_to "Add location", new_event_location_path(@event) %></P>
<% end %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

app/views/events/dashboard.html.erb
<h1>Hallo , dashboard</h1>

<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
      <%= link_to " (XML)", event_path(event, :format => :xml) %>
      <%= link_to " (JSON)", event_path(event, :format => :json) %>
      <%= link_to 'Edit', edit_event_path(event) %>
      <%= button_to 'Delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </li>
    <% end %>
</ul>
<%= link_to 'New Event', new_event_path %>
<%= link_to "Atom feed", events_path(:format => :atom) %>
<%= paginate @events %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

<%= debug(@event) %>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>
<p><%= link_to "Home", root_path %></p>